name: unicon
description: UNICON20 companion application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  http:
  sqflite:
  path:
  ical_parser:
  background_fetch:
  flutter_local_notifications:
  rflutter_alert:
  url_launcher:

  cupertino_icons: ^1.0.2

  flutter_html: ^2.1.1
  flutter_week_view: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - res/
  fonts:
    - family: Tahoma
      fonts:
        - asset: res/font/tahoma.ttf
    - family: Futura
      fonts:
        - asset: res/font/futura/futura.ttf
        - asset: res/font/futura/futura-bold.ttf
          weight: 700
    - family: aAnggota
      fonts:
        - asset: res/font/aAnggota.ttf
    - family: LinLiber
      fonts:
        - asset: res/font/linlibertine/LinLibertine_R.ttf
        - asset: res/font/linlibertine/LinLibertine_RB.ttf
          style: italic
        - asset: res/font/linlibertine/LinLibertine_RBI.ttf
          style: italic
          weight: 700
        - asset: res/font/linlibertine/LinLibertine_RI.ttf
          weight: 700

